// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMEolJzsBAr30y6OfZXMs1U9hB7ybaYco',
    appId: '1:930226561299:web:c9a89e017077caa7087ae6',
    messagingSenderId: '930226561299',
    projectId: 'mula-project',
    authDomain: 'mula-project.firebaseapp.com',
    storageBucket: 'mula-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApHulRZFaGYS4LJAjVEyBlSAw1b8l4eKA',
    appId: '1:930226561299:android:ca632e0587d27056087ae6',
    messagingSenderId: '930226561299',
    projectId: 'mula-project',
    storageBucket: 'mula-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZnVLnPwcwbgI16ThfYuItMVEi2yp9gpI',
    appId: '1:930226561299:ios:f9f52a127a8b9750087ae6',
    messagingSenderId: '930226561299',
    projectId: 'mula-project',
    storageBucket: 'mula-project.appspot.com',
    iosBundleId: 'com.example.trabalho01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZnVLnPwcwbgI16ThfYuItMVEi2yp9gpI',
    appId: '1:930226561299:ios:1e760750eebaa748087ae6',
    messagingSenderId: '930226561299',
    projectId: 'mula-project',
    storageBucket: 'mula-project.appspot.com',
    iosBundleId: 'com.example.trabalho01.RunnerTests',
  );
}
