// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3EhsTORv6J5GgQGsBR1NSQnpQbvDvEn4',
    appId: '1:624649604158:web:0c6e71a67178fe75e2956f',
    messagingSenderId: '624649604158',
    projectId: 'themula-project',
    authDomain: 'themula-project.firebaseapp.com',
    storageBucket: 'themula-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWEshLku_gMf6vHPhe5TK6ndnR_734a1U',
    appId: '1:624649604158:android:6cad3bfa1624c35be2956f',
    messagingSenderId: '624649604158',
    projectId: 'themula-project',
    storageBucket: 'themula-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUIMIVy_I3qVXrV6oNpdBrROq9FgKwzQ',
    appId: '1:624649604158:ios:86bfacae8051933ae2956f',
    messagingSenderId: '624649604158',
    projectId: 'themula-project',
    storageBucket: 'themula-project.appspot.com',
    iosBundleId: 'com.example.trabalho01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeUIMIVy_I3qVXrV6oNpdBrROq9FgKwzQ',
    appId: '1:624649604158:ios:5d9e30f8946ffcf7e2956f',
    messagingSenderId: '624649604158',
    projectId: 'themula-project',
    storageBucket: 'themula-project.appspot.com',
    iosBundleId: 'com.example.trabalho01.RunnerTests',
  );
}
